stages:
  #- test
  - build
  - deploy
  
build_qa:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker build  -f Dockerfile.production.aws -t "$ECR_API_BASE_URL/qa/check/api:$CI_COMMIT_SHA"  .
    - docker push "$ECR_API_BASE_URL/qa/check/api:$CI_COMMIT_SHA"
  only:
    - develop

deploy_qa:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    GITHUB_TOKEN: $GITHUB_TOKEN
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install ecs-deploy==1.7.0
    - ecs deploy ecs-qa  qa-check-api --image qa-check-api-c $ECR_API_BASE_URL/qa/check/api:$CI_COMMIT_SHA  --timeout 3600
    - ecs deploy ecs-qa  qa-check-api-background --image qa-check-api-background $ECR_API_BASE_URL/qa/check/api:$CI_COMMIT_SHA  --timeout 3600
    - echo "new Image was deployed $ECR_API_BASE_URL/qa/check/api:$CI_COMMIT_SHA"
    - echo "Running Migrations"
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker pull $ECR_API_BASE_URL/aws-long-tasks:latest
    #checks if travis tests passed on develop branch
  rules: 
    - if: (curl -q "https://api.travis-ci.org/repos/10142761/branches/develop?access_token=$TRAVIS_API_TOKEN" | grep '"state":"passed"')
      when: manual # the job is only allowed to be manually ran if the condition is met
  only:
    - develop

build_live:
  image: docker:latest
  services:
    - docker:dind
  tags:
    - meedan
    - meedan-labs
  stage: build
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker pull $ECR_API_BASE_URL/aws-long-tasks:latest
  only:
    - master

deploy_live:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  when: manual
  tags:
    - meedan
    - meedan-labs
  variables:
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
    GITHUB_TOKEN: $GITHUB_TOKEN
  script:
    - apk add --no-cache curl jq python py-pip git
    - pip install ecs-deploy==1.7.0
    - ecs deploy ecs-live  live-check-api --image live-check-api-c $ECR_API_BASE_URL/live/check/api:$CI_COMMIT_SHA  --timeout 3600
    - ecs deploy ecs-live  live-check-api-background --image live-check-api-background $ECR_API_BASE_URL/live/check/api:$CI_COMMIT_SHA  --timeout 3600
    - echo "new Image was deployed $ECR_API_BASE_URL/live/check/api:$CI_COMMIT_SHA"
    - echo "Running Migrations"
    - pip install docutils==0.14
    - pip install awscli==1.16.201
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - docker pull $ECR_API_BASE_URL/aws-long-tasks:latest
  only:
    - master